//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnableGPlayWithPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnableGPlayWithPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adb.exe.
        /// </summary>
        internal static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 続ける.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        ///Please check to exist that file..
        /// </summary>
        internal static string Dialog_404_Desc {
            get {
                return ResourceManager.GetString("Dialog_404_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        /// </summary>
        internal static string Dialog_404_Inst {
            get {
                return ResourceManager.GetString("Dialog_404_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adb.exe is not found.
        ///Please check adb.exe&apos;s path..
        /// </summary>
        internal static string Dialog_Adb404_Desc {
            get {
                return ResourceManager.GetString("Dialog_Adb404_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adb.exe is not found.
        /// </summary>
        internal static string Dialog_Adb404_Inst {
            get {
                return ResourceManager.GetString("Dialog_Adb404_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a benesse product tablet.
        ///Would you like continue?.
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Desc {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャレンジタッチが見つかりませんでした.
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Inst {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to grant &quot;{0}&quot; permission to {1}.
        ///Apps may not work perfectly..
        /// </summary>
        internal static string Dialog_PermNotGranted_Desc {
            get {
                return ResourceManager.GetString("Dialog_PermNotGranted_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to grant permission to {0}.
        /// </summary>
        internal static string Dialog_PermNotGranted_Inst {
            get {
                return ResourceManager.GetString("Dialog_PermNotGranted_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googleの機能が使えるようになりました！
        ///タブレットは引き続きご利用になれます.
        /// </summary>
        internal static string Dialog_Successed_Desc {
            get {
                return ResourceManager.GetString("Dialog_Successed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了しました.
        /// </summary>
        internal static string Dialog_Successed_Inst {
            get {
                return ResourceManager.GetString("Dialog_Successed_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数台接続されています。
        ///デバイスは一つだけ接続してください。.
        /// </summary>
        internal static string Dialog_TooManyDevices_Desc {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数台接続されてます.
        /// </summary>
        internal static string Dialog_TooManyDevices_Inst {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバイスと接続できませんでした。
        ///接続を確認してください。.
        /// </summary>
        internal static string Dialog_UnableToConnect_Desc {
            get {
                return ResourceManager.GetString("Dialog_UnableToConnect_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバイスと接続できませんでした.
        /// </summary>
        internal static string Dialog_UnableToConnect_Inst {
            get {
                return ResourceManager.GetString("Dialog_UnableToConnect_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .apk.
        /// </summary>
        internal static string FileSelector_Extension {
            get {
                return ResourceManager.GetString("FileSelector_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APKファイルを開く.
        /// </summary>
        internal static string FileSelector_Title {
            get {
                return ResourceManager.GetString("FileSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インストールを中断する.
        /// </summary>
        internal static string NotGranted_Cancel {
            get {
                return ResourceManager.GetString("NotGranted_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーを無視し、インストールを続行する.
        /// </summary>
        internal static string NotGranted_Continue {
            get {
                return ResourceManager.GetString("NotGranted_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細を隠す.
        /// </summary>
        internal static string NotGranted_HideDetail {
            get {
                return ResourceManager.GetString("NotGranted_HideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細を表示.
        /// </summary>
        internal static string NotGranted_ShowDetail {
            get {
                return ResourceManager.GetString("NotGranted_ShowDetail", resourceCulture);
            }
        }
    }
}
